config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/smart", to: "pages#smart"

  get "/privacy", to: "pages#privacy"
  get '/terms', to:'pages#terms'

  resources :users, only: :show
  get "/dashboard", to: "dashboard#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bounties, except: :destroy do
    resources :solutions, only: [:new, :create, :edit, :update]
    resources :homeworks, only: [:create, :destroy]

  end

  resources :solutions, only: [:show] do
    resources :messages, only: :create
  end
  patch 'solutions/:id', to: 'solutions#custom', as: 'validate_solution'
  # get 'bounty/:id', to: 'dashboard#homework', as: 'add_bounty'


  resources :solutions, only: [:destroy]
  #delete 'solutions/:id', to: 'solutions#destroy', as: 'destroy_solution'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bounty.rb
class Bounty < ApplicationRecord
  belongs_to :user
  has_many :homeworks, dependent: :destroy
  has_many :solutions, dependent: :destroy


  validates :content, :price_cents, :title, presence: true
  # validates :difficulty_level, inclusion: { in: (1..5),
  #   message: "%{value} is not a valid difficulty level you dumb fuck, it goes from 1 to 5" }

  def self.unsolved!
    Bounty.all.each do |bounty|
      if bounty.status == 'pending' && bounty.deadline && (bounty.deadline - (Date.today + 24)).negative?
        bounty.status = 'unsolved'
        bounty.save!
      end
    end
  end
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_bounty, only: [:edit, :show, :update]
  def index
    @notifications = Notification.all
    @bounties = policy_scope(Bounty)
    @min_price = @bounties.sort_by(&:price_cents).first.price_cents
    @max_price = @bounties.sort_by(&:price_cents).last.price_cents
    @bounties = Bounty.all.order(created_at: :desc)
    if params[:query].present?
      sql_query = <<~SQL
        bounties.title  ILIKE :query
        OR users.username ILIKE :query
      SQL
      @bounties = @bounties.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    end

    if params[:min].present? || params[:max].present?
      sql_query = <<~SQL
        price_cents  BETWEEN :min_value AND :max_value
      SQL
      @bounties = @bounties.where(sql_query, min_value: params[:min].to_f || @min_price, max_value: params[:max].to_f||@max_price)
    end
    if params[:difficulty_level].present?
      @bounties = @bounties.where(difficulty_level: params[:difficulty_level].to_i)
    end
  end

  def new
    @bounty = Bounty.new
    authorize @bounty
  end

  def create
    @bounty = Bounty.new(bounties_params)
    @bounty.user = current_user
    # @bounty.price_cents = params[:price_cents]
    authorize @bounty
    if @bounty.save
      redirect_to bounty_path(@bounty)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @message = Message.new
    @solution = Solution.new
    @current_user = current_user
    # if current_user
    #   @solutions = @bounty.user == current_user ? Solution.where(bounty: @bounty) : current_user.solutions.where(bounty: @bounty)
    # else
    #   @solutions = Solution.where(bounty: @bounty)
    # end
    @solutions = Solution.where(bounty: @bounty)
    authorize @bounty
    if @bounty.github_repo.include?('github')
      if @bounty.github_repo.split("/")[4] == "rubyHunters"
        @github_path = "app/controllers/bounties_controller.rb"
      elsif (@repo_name != "rubyHunters")
        @github_path = @bounty.github_repo.split("/")[-3..].join("/")
        @github_name = @bounty.github_repo.split("/")[3]
        @repo_name = @bounty.github_repo.split("/")[4]
      end
    end
    @homework = Homework.new
  end

  def update
    @bounty.update(bounties_params)
    authorize @bounty
    redirect_to bounty_path(@bounty)
  end

  def edit
    authorize @bounty
  end

  private

  def bounties_params
    params.require(:bounty).permit(:title, :content, :price_cents, :github_repo, :deadline, :difficulty_level, :smartcontractaddress)
  end

  def set_bounty
    @bounty = Bounty.find(params[:id])
  end
end

app/views/bounties/edit.html.erb
<h1>Edit bounty</h1>
<div class="container">
	<div class="col-4 offset-4 my-5 pb-5">
		<h2 class="text-center">Edit a bounty </h2>
		<%= simple_form_for(@bounty) do |f| %>
			<%= f.input :title%>
				<%= f.input :content, :placeholder=> "What is your coding problem" %>

						<%= f.input :github_repo %>
							<%= f.submit class: 'btn btn-primary' %>
								<% end %>
	</div>
</div>

app/views/bounties/index.html.erb
<div class="index-container" data-controller="scroll-reveal">

  <div class='grid grid-cols-6 grid-rows-20 '>
    <h2 class="w-screen text-center mt-5">All <span class="green">open</span> bounties</h2>
    <div class='text-white mt-[150px] w-[280px] bg-purple-700 ml-[-20px] p-2 rounded-md no-underline text-center md:ml-[218px]'><%= link_to 'Create a bounty', new_bounty_path, class:'no-underline'%></div>

    <div class='flex row-start-2 justify-center text-center ml-[180px] mt-[20px] md:col-start-3 md:row-start-2 '>
      <%= form_with url: bounties_path, method: :get, html: {class: "d-flex"} do %>
        <%= text_field_tag :query,
            params[:query],
            class: "rounded-md",
            placeholder: " 🔎 "
            %>
        <%#= submit_tag "".html_safe %>
        <%= button_tag 'search', class: "search-btn btn text-white me-1 ms-2 rounded-md inherit" %>


        <%= number_field_tag :min, params[:min] || 0, class: 'd-none' %>
        <%= number_field_tag :max, params[:max] || 50000, class: 'd-none' %>
      <% end %>
    </div>

<%# Filter box  %>
    <div class='col-start-1 row-start-5 col-span-6 mt-2 rounded-xl bg-inherit ml-[20px] md:w-[350px] md:col-span-1'>
      <div class="bg-purple-700 reveal rounded-xl md:mt-[25px]" data-scroll-reveal-target="item">
        <p class="text-center mb-5 text-white pt-2">Price range</p>
        <%= form_with url: bounties_path,
                      method: :get,
                      html: {
                        data: {
                          controller: "range-input",
                          "range-input-min-value" => params[:min]|| @min_price ,
                          "range-input-max-value" => params[:max] || @max_price,
                          "range-input-max-price-value" => @max_price,
                          class: "pricing-filter"
                        }
                      } do %>
          <div class="price-box" data-range-input-target="range"></div>
          <%= text_field_tag :min, params[:min] || @min_price, 'data-range-input-target' => 'minInput', class: 'd-none' %>
          <%= text_field_tag :max, params[:max] || @max_price, 'data-range-input-target' => 'maxInput', class: 'd-none' %>
          <div class="tag-item difficulty-box">

          </div>
          <div class="btn-filter w-100">
            <%= submit_tag 'Apply', class: "btn chat-btn mb-2 mt-3 w-100" %>

            <%= text_field_tag :query,
              params[:query],
              class: "d-none"
            %>
          </div>
        <% end %>
      </div>
    </div>


<%# Bounties card %>


      <div class=' bounties-card row-start-7 ml-[25px] md:col-start-3 md:col-span-4 md:row-start-5'>
        <% @bounties.each_with_index do |bounty, i| %>
          <div class="bounty-card border-4 rounded-lg border-purple-700 hover:bg-purple-700 w-[350px] h-[250px] sm:gap-[5px] reveal grid grid-cols-1 gap-1 grid-rows-1 md:flex justify-between md:w-[650px] md:h-[100px] md:col-span-6" data-scroll-reveal-target="item" data-delay="<%= i*20 %>ms" >
            <%= link_to bounty_path(bounty), class:" text-decoration-none text-white" do %>
              <div class="">
                <div class="md:flex ">

                <div class="bounty-links ml-auto mr-auto row-start-2 col-start-3 col-span-3 md:mr-10 mt-3">
                  <% if bounty.user.photo.attached? %>
                    <%  %>
                    <%= cl_image_tag bounty.user.photo.key, class:"avatar-bounty" %>
                  <% else %>
                    <div class=''>
                      <%= image_tag(["robot1.png", "robot2.png", "robot3.png"].sample, class:"avatar-bounty w-15") %>
                    </div>
                  <% end %>
                  <p class="title"><%= bounty.user.username %></p>
                </div>
                  <div>
                  <p class="text-lg mt-3 text-center mx-1 md:mx-0"><%= bounty.title[0..40]%>
                   <% if bounty.title.length > 40 %>...
                   <% end %>
                  </p>

                 <div class='md:flex'>
                  <p class="text-base text-green-600 text-center"> <span class='text-xl'>⏱ </span>
                  <% if bounty.deadline == nil %>
                      <%= "none" %>
                    <% else %>
                      <%= bounty.deadline %>
                    <% end %>  </p>
                <div class="">
                  <p class="text-base md:ml-9 text-center"><span class='text-xl'>💰 </span><%= bounty.price_cents %> €</p>
                </div>
                <div class="pt-2">
                  <p class=" md:ml-9 text-center text-gray-300w-[100px] h-[20%] text-xs animate-pulse"><span class='text-xs md:text-xs'>Created at: </span ><%= bounty.created_at.strftime("%d %B") %></p>
                </div>
              </div>



                </div>
                </div>
              </div>
            <% end %>






          </div>
        <% end %>
      </div>

  </div>
</div>

app/views/bounties/new.html.erb
<div id="create-bounty">
  <div class ="pimp" data-controller="withdraw">
    <h5 class="text-center">Create a <span class="green">bounty</span></h5>
    <%= simple_form_for @bounty do |f| %>
      <div class="create-bounty-all md:flex md:justify-evenly">
        <div class="md:h-[300px] md:mt-[-100px] md:w-[50%] md:max-w-[50%] md:flex md:justify-between md:flex-col">
          <span class="formfont" ><%= f.input :title, label: false, placeholder: 'Title'%></span>
          <span class="formfont" ><%= f.input :company, label:false, placeholder: 'Company'%></span>
          <span class="formfont mt-20"><%= f.input :price_cents, label: false, :placeholder => "Price in € for your bounty"%> <div class='text-gray-400 text-xs'>The payment method is chosen in consultation with both parties (fiat, crypto, …)</div></span>


        </div>
        <div class="md:h-[400px] md:w-[50%] md:max-w-[50%] md:flex md:justify-between md:flex-col">
          <span class="formfont"><%= f.input :deadline, as: :string, input_html: { data: { controller: 'flatpickr' } }, label: false, placeholder: 'Optional: chose a deadline' %></span>
          <span class="formfont"><%= f.input :github_repo, label: false, :placeholder => "Link to your code"%></span>
          <span class="formfont"><%= f.input :content, label: false, :placeholder => "Detail your coding problem" %>
          <div class='text-xs text-gray-400'>Provide your contact information (email, Discord, LinkedIn, …) to enable a direct communication with the developer</div></span>

          <div class=" align-items-center justify-content-between md:flex">
            <!--<p id="contractAccount">Contract Account: Not Connected</p>
              <%= f.input :smartcontractaddress, label: false, input_html: { data: { withdraw_target:'smartid'}, class:"d-none"} %>
              <button type="button" class="green-create" data-withdraw-target="connectContract" data-action="click->withdraw#connectContract click->withdraw#getContractAccount">Connect to contract</button>-->
          </div>
          <div id="writeArea" class=" align-items-center justify-content-between d-none md:flex" data-withdraw-target="depositButton">
            <div class=" input-group">
              <%= number_field_tag :price_cents, '1', class:"form-control", id:"depositInput", :placeholder => "Price" %>
              <div class="input-group-append">
                <span class="input-group-text">ETH</span>
              </div>
            </div>
            <button type="button" class="green-create" data-action="click->withdraw#depositContract">Send money to contract</button>
          </div>
          <div class=' md:ml-[-120px] md:mb-[100px]'>
          <%= f.submit class: 'button2'%>
          </div>
        </div>
        <%# <span class="formfont"><%= f.input :deadline, :input_html => {:value => Time.now}, start_year: Time.now.year, start_month: Time.now.month, start_day: Time.now.day</span> %>
      </div>
    <% end %>
  </div>
</div>