config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/smart", to: "pages#smart"

  get "/privacy", to: "pages#privacy"
  get '/terms', to:'pages#terms'

  resources :users, only: :show
  get "/dashboard", to: "dashboard#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bounties, except: :destroy do
    resources :solutions, only: [:new, :create, :edit, :update]
    resources :homeworks, only: [:create, :destroy]

  end

  resources :solutions, only: [:show] do
    resources :messages, only: :create
  end
  patch 'solutions/:id', to: 'solutions#custom', as: 'validate_solution'
  # get 'bounty/:id', to: 'dashboard#homework', as: 'add_bounty'


  resources :solutions, only: [:destroy]
  #delete 'solutions/:id', to: 'solutions#destroy', as: 'destroy_solution'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :bounty
  belongs_to :user

  has_many :messages, dependent: :destroy

  validates :content, presence: true
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  before_action :set_bounty, only: %i[new edit update create]
  before_action :set_solution, only: %i[show edit destroy custom]

  def show
    @message = Message.new
    @bounty = @solution.bounty
    @other_user = current_user == @bounty.user ? @solution.user : @bounty.user
    authorize @solution
  end

  def new
    @solution = Solution.new
    authorize @solution
  end

  def create
    @solution = Solution.new(solution_params)
    authorize @solution
    @solution.bounty = @bounty
    @solution.user = current_user
    if @solution.save
      Notification.create(
      user: @solution.bounty.user,
      content: "New solution from #{current_user.username}")
      redirect_to bounty_path(@bounty)
    else
      @solutions = @bounty.user == current_user ? Solution.where(bounty: @bounty) : current_user.solutions.where(bounty: @bounty)
      @message = Message.new
      render "bounties/show", status: :unprocessable_entity
    end
  end

  def edit
    @solution = Solution.find(params[:id])
    authorize @solution
  end

  def update
    @solution = Solution.find(params[:id])
    @solution.update(solution_params)
    authorize @solution
    if @solution.save
      redirect_to bounty_path(@bounty)
    else
      @solutions = @bounty.user == current_user ? Solution.where(bounty: @bounty) : current_user.solutions.where(bounty: @bounty)
      @message = Message.new
      render "bounties/show", status: :unprocessable_entity
    end
  end

  def destroy
    @solution.destroy
    authorize @solution
    redirect_to bounty_path(@solution.bounty), status: :see_other
  end

  def custom
    authorize @solution
    @solution.bounty.solutions.each do |solution|
      unless @solution == solution
        solution.status = "denied"
        solution.save
      end
    end
    @solution.status = "accepted"
    @solution.save
    @solution.bounty.status = "solved"
    @solution.bounty.save
    @solution.user.update_ranking
    redirect_to bounty_path(@solution.bounty)
  end

  private

  def solution_params
    params.require(:solution).permit(:content, :github_repo)
  end

  def set_bounty
    @bounty = Bounty.find(params[:bounty_id])
  end

  def set_solution
    @solution = Solution.find(params[:id])
  end
end

app/views/solutions/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-solution-id-value="<%= @solution.id %>"
  >
  <h1>#Solution id: <%= @solution.id %> </h1>

  <h2>Solution status: <%= @solution.status %></h2>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @solution.messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <%= render "messages/message", message: message %>
      </div>
    <% end %>
  </div>
  <%= simple_form_for [@solution, @message],
    html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
  %>
    <%= f.input :content,
      label: false,
      # placeholder: "Message ##{@other_user.username}",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>

  <% if @solution.bounty.user == current_user && @solution.status == nil || @solution.status == "pending" %>
    <%= link_to "Validate this solution", validate_solution_path(@solution), class: "btn btn-primary", data: {turbo_method: :patch, turbo_confirm: 'Are you sure you want to confirm this solution?'} %>
  <% end %>
</div>